# Generated by Django 4.1.5 on 2023-01-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="code",),
        migrations.RemoveField(model_name="room", name="guest_can_pause",),
        migrations.RemoveField(model_name="room", name="host",),
        migrations.RemoveField(model_name="room", name="votes_to_skip",),
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, max_length=222),
        ),
    ]
